# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mf.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def __init__(self):
        self.label = None
        self.frame = None
        self.carnum = None
        self.frame_5 = None
        self.video1 = None

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(993, 696)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 120, 971, 571))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.video1 = QtWidgets.QLabel(self.frame)
        self.video1.setGeometry(QtCore.QRect(-10, 0, 961, 561))
        self.video1.setObjectName("video1")
        self.frame_5 = QtWidgets.QFrame(Dialog)
        self.frame_5.setGeometry(QtCore.QRect(10, 69, 151, 41))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setGeometry(QtCore.QRect(10, 0, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_6 = QtWidgets.QFrame(Dialog)
        self.frame_6.setGeometry(QtCore.QRect(170, 70, 221, 41))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.carnum = QtWidgets.QLabel(self.frame_6)
        self.carnum.setGeometry(QtCore.QRect(0, 0, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.carnum.setFont(font)
        self.carnum.setStyleSheet("color:red\n"
                                  "")
        self.carnum.setObjectName("carnum")
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(170, 20, 631, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 991, 691))
        self.label_2.setStyleSheet("            font-family: \"Arial\";\n"
                                   "            font-size: 24px;\n"
                                   "            font-weight: bold;\n"
                                   "            color: white;\n"
                                   "            background-color: green;  /* 绿色背景 */\n"
                                   "            border: 2px solid white;\n"
                                   "            border-radius: 10px;\n"
                                   "            padding: 10px;\n"
                                   "            text-align: center;\n"
                                   "background-image: url(\"D:/大三下/企业实训/资料/day03/pythonProjectQT/data/bg3.jpg\");\n"
                                   "            background-position: center;\n"
                                   "            background-repeat: no-repeat;\n"
                                   "            background-size: cover;  /* 调整背景图片的大小，使其覆盖标签 */")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.frame.raise_()
        self.frame_5.raise_()
        self.frame_6.raise_()
        self.title.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.video1.setText(_translate("Dialog", "TextLabel"))
        self.label.setText(_translate("Dialog", "东门-车流流量:"))
        self.carnum.setText(_translate("Dialog", "0"))
        self.title.setText(_translate("Dialog", "人车流量监控系统"))
        self.label_2.setText(_translate("Dialog", "TextLabel"))
